#!/bin/bash
# ============================================================
#  3-init-site.sh  — 在新服务器为单个 site 创建基础设施
#
#  做的事:
#    1. 从 sites.csv 读出 domain
#    2. 从 secrets/{NN}.secrets 读出 jwt_secret + voice_relay_secret
#    3. 创建 PG database imhub_NN + user imhub_NN
#    4. 写 /opt/im-hub/sites/NN/config.yaml
#    5. 软链 static 静态资源
#    6. 创建 nginx server block (含 /api/call/audio WebSocket 配置)
#    7. 申请 Let's Encrypt SSL
#    8. 启用 + 启动 systemd 服务
#
#  用法:
#    bash 3-init-site.sh 03                    # 用默认 sites.csv
#    bash 3-init-site.sh 03 --skip-ssl         # 跳过 SSL (先 HTTP 测)
#    bash 3-init-site.sh 03 --sites-csv ...    # 用自定义 csv
# ============================================================
set -euo pipefail

BASE_DIR="/opt/im-hub"
SITES_DIR="${BASE_DIR}/sites"
SECRETS_DIR="${BASE_DIR}/secrets"
SRC_DIR="${BASE_DIR}/src"
BIN_DIR="${BASE_DIR}/bin"
SITES_CSV="${BASE_DIR}/sites.csv"
SKIP_SSL=0

# ---------- 参数 ----------
SITE_ID="${1:-}"
shift || true
while [[ $# -gt 0 ]]; do
    case $1 in
        --skip-ssl) SKIP_SSL=1; shift ;;
        --sites-csv) SITES_CSV="$2"; shift 2 ;;
        *) echo "unknown: $1"; exit 1 ;;
    esac
done

[[ "$SITE_ID" =~ ^[0-9]{2}$ ]] || { echo "用法: bash 3-init-site.sh <两位 site_id, 如 03>"; exit 1; }

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'
info()  { echo -e "${GREEN}[INFO]${NC}  $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*"; exit 1; }

[ "$(id -u)" -eq 0 ] || error "请用 root"
[ -f "$SITES_CSV" ] || error "找不到 $SITES_CSV，请先上传"

# ---------- 1. 从 csv 读出 domain ----------
DOMAIN=$(awk -F',' -v sid="$SITE_ID" '$1==sid{print $2}' "$SITES_CSV")
[ -n "$DOMAIN" ] || error "site_id=$SITE_ID 在 $SITES_CSV 里找不到"
PORT=$((8080 + 10#$SITE_ID))
DB_NAME="imhub_${SITE_ID}"
DB_USER="imhub_${SITE_ID}"
SITE_DIR="${SITES_DIR}/${SITE_ID}"

info "==========================================="
info "  初始化 site ${SITE_ID}"
info "  域名: ${DOMAIN}"
info "  端口: ${PORT}"
info "  数据库: ${DB_NAME}"
info "==========================================="

# ---------- 2. 读 secrets ----------
SECRETS_FILE="${SECRETS_DIR}/site_${SITE_ID}.secrets"
[ -f "$SECRETS_FILE" ] || error "找不到 $SECRETS_FILE，请先上传 audit 阶段生成的 secrets 文件"

# 用 . 加载文件 (KEY=VALUE 格式)
set -a; source "$SECRETS_FILE"; set +a

[ -n "${jwt_secret:-}" ] || error "$SECRETS_FILE 缺少 jwt_secret"
[ -n "${voice_relay_secret:-}" ] || warn "voice_relay_secret 为空（语音功能可能不可用）"

# 校验 source_domain 是否和 csv 一致
if [ "${source_domain:-}" != "$DOMAIN" ]; then
    warn "⚠️  secrets 里的 source_domain=${source_domain:-空} 与 csv 里的 ${DOMAIN} 不一致！"
    warn "    你可能搞错了 secrets 文件归属，是否继续? (yes/NO)"
    read CONFIRM
    [ "$CONFIRM" = "yes" ] || error "已取消"
fi

# ---------- 3. 创建 PG database (密码持久化, 避免重跑改密导致连接断) ----------
# 密码文件: /opt/im-hub/secrets/db_pass_NN
DB_PASS_FILE="${SECRETS_DIR}/db_pass_${SITE_ID}"

USER_EXISTS=$(sudo -u postgres psql -tAc "SELECT 1 FROM pg_roles WHERE rolname='${DB_USER}';" 2>/dev/null)

if [ -z "$USER_EXISTS" ]; then
    # 首次创建: 生成新密码并保存
    info "创建 PG 用户 $DB_USER ..."
    DB_PASS=$(openssl rand -hex 24)
    sudo -u postgres psql -c "CREATE USER ${DB_USER} WITH PASSWORD '${DB_PASS}';" >/dev/null
    echo "$DB_PASS" > "$DB_PASS_FILE"
    chmod 600 "$DB_PASS_FILE"
elif [ -f "$DB_PASS_FILE" ]; then
    # 用户存在且我们记得密码: 重用 (不改, 否则运行中的进程会断)
    info "PG 用户 $DB_USER 已存在, 复用既有密码"
    DB_PASS=$(cat "$DB_PASS_FILE")
else
    # 用户存在但密码丢失: 必须重置 (会导致正在运行的进程断连, 但只是 systemd 自动重启)
    warn "PG 用户 $DB_USER 存在但密码文件丢失, 重置密码 (运行中的实例会断连后自动重连)"
    DB_PASS=$(openssl rand -hex 24)
    sudo -u postgres psql -c "ALTER USER ${DB_USER} WITH PASSWORD '${DB_PASS}';" >/dev/null
    echo "$DB_PASS" > "$DB_PASS_FILE"
    chmod 600 "$DB_PASS_FILE"
fi

# 检查库是否已存在
if sudo -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname='${DB_NAME}';" | grep -q 1; then
    warn "database ${DB_NAME} 已存在, 跳过创建"
else
    info "创建 PG database $DB_NAME ..."
    sudo -u postgres createdb -O "$DB_USER" "$DB_NAME"
fi

# ---------- 4. 创建目录 ----------
info "创建 site 目录 $SITE_DIR ..."
mkdir -p "${SITE_DIR}/data/uploads"
mkdir -p "${SITE_DIR}/data/Emoji"   # 表情资源, 5-restore-new.sh 会写入用户的自定义表情

# ---------- 5. 软链共享静态资源 ----------
# WorkingDirectory 是 site 目录，im-agent-hub 会从 ./static 读
ln -sfn "${SRC_DIR}/server/static" "${SITE_DIR}/static"

# ---------- 6. 写 config.yaml ----------
info "写 ${SITE_DIR}/config.yaml ..."
cat > "${SITE_DIR}/config.yaml" <<EOF
# Auto-generated by 3-init-site.sh for site ${SITE_ID} (${DOMAIN})

server:
  port: ${PORT}
  jwt_secret: "${jwt_secret}"

database:
  host: localhost
  port: 5432
  user: ${DB_USER}
  password: ${DB_PASS}
  dbname: ${DB_NAME}

admin:
  username: "admin"
  password: "admin123"

cleanup:
  enabled: true
  retention_days: 30
  cron: "0 3 * * *"

voice_relay:
  secret: "${voice_relay_secret:-}"
  relay_ws_url: ""    # empty = use self (per-site relay, plan A)
EOF
chmod 600 "${SITE_DIR}/config.yaml"

# ---------- 7. systemd 启用 (但先不启动，等数据导入后再启动) ----------
info "启用 im-hub@${SITE_ID} (暂不启动，等数据导入后再 start)..."
systemctl enable "im-hub@${SITE_ID}" >/dev/null 2>&1

# ---------- 8. Nginx server block ----------
info "写 nginx 配置 (含 /api/call/audio WebSocket)..."
NGINX_CONF="/etc/nginx/sites-available/${DOMAIN}"
cat > "$NGINX_CONF" <<NGINXEOF
# Auto-generated by 3-init-site.sh for site ${SITE_ID}
server {
    listen 80;
    listen [::]:80;
    server_name ${DOMAIN} www.${DOMAIN};

    client_max_body_size 50m;

    # H5 / admin / 静态资源 / 普通 API
    location / {
        proxy_pass http://127.0.0.1:${PORT};
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }

    # IM 主 WebSocket
    location /api/ws {
        proxy_pass http://127.0.0.1:${PORT};
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_read_timeout 86400s;
        proxy_send_timeout 86400s;
    }

    # 客服端 WebSocket
    location /api/service/ws {
        proxy_pass http://127.0.0.1:${PORT};
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_read_timeout 86400s;
        proxy_send_timeout 86400s;
    }

    # ★ 语音中转 WebSocket (旧 deploy-bare.sh 遗漏了这个！)
    location /api/call/audio {
        proxy_pass http://127.0.0.1:${PORT};
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_read_timeout 86400s;
        proxy_send_timeout 86400s;
        # 音频帧通常 < 4KB，但留点缓冲
        proxy_buffering off;
    }
}
NGINXEOF

ln -sf "$NGINX_CONF" "/etc/nginx/sites-enabled/${DOMAIN}"
nginx -t || error "nginx 配置语法错误"
systemctl reload nginx

# ---------- 9. SSL ----------
if [ "$SKIP_SSL" -eq 0 ]; then
    info "申请 Let's Encrypt SSL (${DOMAIN}, www.${DOMAIN})..."
    if certbot --nginx -d "$DOMAIN" -d "www.$DOMAIN" \
       --non-interactive --agree-tos --register-unsafely-without-email --redirect; then
        info "SSL 申请成功"
    else
        warn "SSL 申请失败 (域名可能还没解析到这台服务器)"
        warn "等 DNS 切过来后手动跑: certbot --nginx -d $DOMAIN -d www.$DOMAIN"
    fi
fi

# ---------- 10. 完成 ----------
echo ""
info "==========================================="
info "  ✅ site ${SITE_ID} 基础设施就绪"
info "==========================================="
echo "  域名:       ${DOMAIN}"
echo "  端口:       ${PORT}"
echo "  数据库:     ${DB_NAME} (空，等数据导入)"
echo "  配置文件:   ${SITE_DIR}/config.yaml"
echo "  systemd:    im-hub@${SITE_ID} (enabled, NOT started)"
echo ""
echo "  下一步:"
echo "    在旧服务器 ${SITE_ID} 上跑 4-export-old.sh 导出数据"
echo "    rsync 过来后跑:"
echo "      bash 5-restore-new.sh --site-id ${SITE_ID} --source-domain ${DOMAIN}"
echo ""
